export const paths = {
  home: '/',
  auth: { signIn: '/auth/sign-in', signUp: '/auth/sign-up', resetPassword: '/auth/reset-password', forgotPassword: '/auth/forgot-password' },
  dashboard: {
    overview: '/dashboard',
    account: '/dashboard/account',
    customers: '/dashboard/customers',
    integrations: '/dashboard/integrations',
    settings: '/dashboard/settings',
  },
  admin: {
    dashboard: '/admin/dashboard',
    profile: '/admin/profile',
    productManager: '/admin/product-manager',
    categories: '/admin/product-manager/categories',
    products: '/admin/product-manager/products',
    productUnits: '/admin/product-manager/units',
    clothing: '/admin/product-manager/clothing',
    clothingColors: '/admin/product-manager/clothing/colors',
    clothingSeasons: '/admin/product-manager/clothing/seasons',
    clothingCollections: '/admin/product-manager/clothing/collections',
    clothingSizes: '/admin/product-manager/clothing/sizes',
    clothingMaterials: '/admin/product-manager/clothing/materials',
    sales: '/admin/sales',
    purchases: '/admin/purchases',
    expenses: '/admin/expenses',
    expenseCategories: '/admin/expenses/categories',
    payments: '/admin/payments',
    paymentIn: '/admin/payments-in',
    paymentOut: '/admin/payments-out',
    paymentModes: '/admin/payment-modes',
    parties: '/admin/parties',
    users: '/admin/users',
    companies: '/admin/companies',
    stores: '/admin/stores',
    reports: '/admin/reports',
    invoiceVerification: '/admin/invoice-verification',
    inventorySearch: '/admin/inventory-search',
    predictions: '/admin/predictions',
    stock: '/admin/stock',
    stockTransfers: '/admin/stock-transfers',
    activityLogs: '/admin/activity-logs',
    settings: '/admin/settings',
  },
  stockManager: {
    dashboard: '/stock-manager/dashboard',
    parties: '/stock-manager/parties',
    suppliers: '/stock-manager/parties/suppliers',
    purchases: '/stock-manager/purchases',
    expenses: '/stock-manager/expenses',
    payments: '/stock-manager/payments',
    paymentOut: '/stock-manager/payments/payments-out',
    reports: '/stock-manager/reports',
    paymentReports: '/stock-manager/reports/payments',
    userReports: '/stock-manager/reports/users',
    expenseReports: '/stock-manager/reports/expenses',
    invoiceVerification: '/stock-manager/invoice-verification',
    profile: '/stock-manager/profile',
    inventorySearch: '/stock-manager/inventory-search',
    stockTransfers: '/stock-manager/stock-transfers',
    sales: '/stock-manager/sales',
  },
  superAdmin: {
    dashboard: '/super-admin/dashboard',
    companies: '/super-admin/companies',
    subscriptionPlans: '/super-admin/subscription-plans',
    currencies: '/super-admin/currencies',
    profile: '/super-admin/profile',
  },
  salesman: {
    dashboard: '/salesman/dashboard',
    parties: '/salesman/parties',
    customers: '/salesman/parties/customers',
    sales: '/salesman/sales',
    paymentIn: '/salesman/sales/payments-in',
    expenses: '/salesman/expenses',
    reports: '/salesman/reports',
    paymentReports: '/salesman/reports/payments',
    userReports: '/salesman/reports/users',
    expenseReports: '/salesman/reports/expenses',
    invoiceVerification: '/salesman/invoice-verification',
    profile: '/salesman/profile',
    inventorySearch: '/salesman/inventory-search',
  },
  errors: { notFound: '/errors/not-found' },
} as const; 