import type { ColorSystemOptions } from '@mui/material/styles';

import { amber, deepPurple, kepple, nevada, primaryTeal, redOrange, roseShade, shakespeare, stormGrey, vividPurple } from './colors';
import type { ColorScheme } from './types';

export const colorSchemes = {
  dark: {
    palette: {
      action: { 
        disabledBackground: 'rgba(0, 0, 0, 0.12)',
        hover: 'rgba(255, 255, 255, 0.08)',
        focus: 'rgba(255, 255, 255, 0.12)',
        selected: 'rgba(255, 255, 255, 0.16)',
        active: 'rgba(255, 255, 255, 0.24)',
      },
      background: {
        default: 'var(--mui-palette-neutral-950)',
        defaultChannel: '2 6 23',
        paper: 'var(--mui-palette-neutral-900)',
        paperChannel: '15 23 42',
        level1: 'var(--mui-palette-neutral-800)',
        level2: 'var(--mui-palette-neutral-700)',
        level3: 'var(--mui-palette-neutral-600)',
      },
      common: { black: '#000000', white: '#ffffff' },
      divider: 'var(--mui-palette-neutral-700)',
      dividerChannel: '51 65 85',
      error: {
        ...redOrange,
        light: redOrange[300],
        main: redOrange[400],
        dark: redOrange[500],
        contrastText: 'var(--mui-palette-common-black)',
      },
      info: {
        ...shakespeare,
        light: shakespeare[300],
        main: shakespeare[400],
        dark: shakespeare[500],
        contrastText: 'var(--mui-palette-common-black)',
      },
      neutral: { ...nevada },
      primary: {
        ...primaryTeal,
        light: primaryTeal[300],
        main: primaryTeal[500],
        dark: primaryTeal[700],
        contrastText: 'var(--mui-palette-common-white)',
      },
      secondary: {
        ...deepPurple,
        light: deepPurple[300],
        main: deepPurple[500],
        dark: deepPurple[700],
        contrastText: 'var(--mui-palette-common-white)',
      },
      success: {
        ...kepple,
        light: kepple[300],
        main: kepple[400],
        dark: kepple[500],
        contrastText: 'var(--mui-palette-common-black)',
      },
      text: {
        primary: 'var(--mui-palette-neutral-100)',
        primaryChannel: '241 245 249',
        secondary: 'var(--mui-palette-neutral-400)',
        secondaryChannel: '148 163 184',
        disabled: 'var(--mui-palette-neutral-600)',
      },
      warning: {
        ...amber,
        light: amber[300],
        main: amber[500],
        dark: amber[700],
        contrastText: 'var(--mui-palette-common-black)',
      },
      accent: {
        ...roseShade,
        light: roseShade[300],
        main: roseShade[500],
        dark: roseShade[700],
        contrastText: 'var(--mui-palette-common-white)',
      },
    },
  },
  light: {
    palette: {
      action: { 
        disabledBackground: 'rgba(0, 0, 0, 0.06)',
        hover: 'rgba(0, 0, 0, 0.04)',
        focus: 'rgba(0, 0, 0, 0.08)',
        selected: 'rgba(0, 0, 0, 0.12)',
        active: 'rgba(0, 0, 0, 0.16)',
      },
      background: {
        default: 'var(--mui-palette-common-white)',
        defaultChannel: '255 255 255',
        paper: 'var(--mui-palette-common-white)',
        paperChannel: '255 255 255',
        level1: 'var(--mui-palette-neutral-50)',
        level2: 'var(--mui-palette-neutral-100)',
        level3: 'var(--mui-palette-neutral-200)',
      },
      common: { black: '#000000', white: '#ffffff' },
      divider: 'var(--mui-palette-neutral-200)',
      dividerChannel: '226 232 240',
      error: {
        ...redOrange,
        light: redOrange[400],
        main: redOrange[500],
        dark: redOrange[600],
        contrastText: 'var(--mui-palette-common-white)',
      },
      info: {
        ...shakespeare,
        light: shakespeare[400],
        main: shakespeare[500],
        dark: shakespeare[600],
        contrastText: 'var(--mui-palette-common-white)',
      },
      neutral: { ...stormGrey },
      primary: {
        ...primaryTeal,
        light: primaryTeal[400],
        main: primaryTeal[500],
        dark: primaryTeal[600],
        contrastText: 'var(--mui-palette-common-white)',
      },
      secondary: {
        ...deepPurple,
        light: deepPurple[400],
        main: deepPurple[500],
        dark: deepPurple[600],
        contrastText: 'var(--mui-palette-common-white)',
      },
      success: {
        ...kepple,
        light: kepple[400],
        main: kepple[500],
        dark: kepple[600],
        contrastText: 'var(--mui-palette-common-white)',
      },
      text: {
        primary: 'var(--mui-palette-neutral-900)',
        primaryChannel: '15 23 42',
        secondary: 'var(--mui-palette-neutral-500)',
        secondaryChannel: '100 116 139',
        disabled: 'var(--mui-palette-neutral-400)',
      },
      warning: {
        ...amber,
        light: amber[400],
        main: amber[500],
        dark: amber[600],
        contrastText: 'var(--mui-palette-common-white)',
      },
      accent: {
        ...roseShade,
        light: roseShade[400],
        main: roseShade[500], 
        dark: roseShade[600],
        contrastText: 'var(--mui-palette-common-white)',
      },
    },
  },
} satisfies Partial<Record<ColorScheme, ColorSystemOptions>>;
